"""criacao inicial das tabelas de staging

Revision ID: cd660b2d2cf6
Revises:
Create Date: 2026-09-13 12:02:10.835593

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "cd660b2d2cf6"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
